{{- if .Values.mailjetService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.mailjetService.secretName }}"
  labels:
    {{- include "go-mail-service.labels" . | nindent 4 }}
stringData:
  mailjetApiKeyPublic: "{{ .Values.mailjetService.apiKeyPublic }}"
  mailjetApiKeyPrivate: "{{ .Values.mailjetService.apiKeyPrivate }}"
{{- end }}
